apiVersion: v1
kind: ConfigMap
metadata:
  name: perf-sidecar-injector-webhook-configmap
data:
  sidecarconfig.yaml: |
    policy: enabled
    containers:
      - name: perf-sidecar
        image: namnx228/k8s-multitenancy-sidecar-container-amd64-2:latest
        imagePullPolicy: Always
        # stdin: true
        # tty: true
        securityContext:
          capabilities:
            add:
              - NET_ADMIN
              - NET_RAW
            # privileged: true
        volumeMounts:
            - name: perf-output
              mountPath: /out
    volumes:
      - name: perf-output
        hostPath:
            path: /out
            type: DirectoryOrCreate
    # ShareProcessNamespace: true
