apiVersion: apps/v1
kind: Deployment
metadata:
  name: perf-sidecar-injector-webhook-deployment
  labels:
    app: perf-sidecar-injector
spec:
  selector:
    matchLabels:
      app: perf-sidecar-injector
  replicas: 1
  template:
    metadata:
      labels:
        app: perf-sidecar-injector
    spec:
      containers:
        - name: perf-sidecar-injector
          image: namnx228/perf-sidecar-injector-amd64:latest
          # imagePullPolicy: Always # For development

          imagePullPolicy: IfNotPresent # For evaluation
          args:
            - -sidecarCfgFile=/etc/webhook/config/sidecarconfig.yaml
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
            - name: webhook-config
              mountPath: /etc/webhook/config
      volumes:
        - name: webhook-certs
          secret:
            secretName: perf-sidecar-injector-webhook-certs
        - name: webhook-config
          configMap:
            name: perf-sidecar-injector-webhook-configmap
